version: '2'

services:
  api:
    build:
      context: .
      target: api
    ports:
      - 3000:3000
    command: go run cmd/api/main.go
    volumes:
      - .:/app
    networks:
      - base
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  load:
    build:
      context: .
      target: base
    command: go run cmd/loadCreator/main.go
    volumes:
      - .:/app
    depends_on: 
      - api
    networks:
      - base

  postgresql:
    image: docker.io/bitnami/postgresql:15
    volumes:
      - db:/bitnami/postgresql
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      POSTGRES_DB: messager
    networks:
      - base

  pgbouncer:
    image: docker.io/bitnami/pgbouncer
    ports:
      - 6432
    environment:
      POSTGRESQL_HOST: postgresql
      PGBOUNCER_AUTH_TYPE: trust
      PGBOUNCER_DATABASE: messager
    networks:
      - base
    depends_on:
      - postgresql

  pghero:
    image: ankane/pghero
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgresql:5432/messager
    networks:
      - base

volumes:
  db:

networks:
  base:
