version: '2'

services:
  frontend:
    build:
      context: frontend/.
      target: dev
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on: 
      - api
    networks:
      - base

  api:
    build:
      context: go-backend/.
      target: api
    ports:
      - 3001:3000
    command: go run cmd/api/main.go
    volumes:
      - ./go-backend:/app
    networks:
      - base
    depends_on: 
      - postgres
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/health || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  load:
    build:
      context: loader/.
      target: base
    command: go run cmd/main.go
    volumes:
      - ./loader:/app
    depends_on: 
      - api
    networks:
      - base

  postgres:
    image: postgres:15
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_app
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - base
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf

volumes:
  db:
  node_modules:

networks:
  base:
